export type ParsedCollectionRow={dueDate:string;patientName:string;cpf:string|null;responsible:string|null;paymentMethod:string|null;openAmountCents:number;receivedAmountCents:number;notes:string|null;protested:boolean;settled:boolean;sourceSheet:string;sourceRow:number;unit:"Sorocaba"};
export type ParsedNegotiation={date:string;patientName:string;monthLabel:string|null;negotiatedAmountCents:number;receivedAmountCents:number;paymentMethod:string|null;notes:string|null;sourceRow:number};
export type CollectionsWorkbookParseResult={rows:ParsedCollectionRow[];negotiations:ParsedNegotiation[];sheets:string[]};
const normalize=(v:unknown)=>String(v??"").normalize("NFD").replace(/[\u0300-\u036f]/g,"").toLowerCase().replace(/[^a-z0-9]/g,"");
const text=(v:unknown)=>String(v??"").replace(/\s+/g," ").trim();
function moneyNumber(v:unknown){if(typeof v==="number"&&Number.isFinite(v))return v;const raw=text(v);if(!raw)return 0;const clean=raw.replace(/R\$/gi,"").replace(/\s/g,"");const n=clean.includes(",")?clean.replace(/\./g,"").replace(",","."):clean;const p=Number(n.replace(/[^0-9.-]/g,""));return Number.isFinite(p)?p:0}
function iso(y:number,m:number,d:number){const x=new Date(Date.UTC(y,m-1,d));return x.getUTCFullYear()===y&&x.getUTCMonth()===m-1&&x.getUTCDate()===d?`${String(y).padStart(4,"0")}-${String(m).padStart(2,"0")}-${String(d).padStart(2,"0")}`:null}
function parseDate(v:unknown,XLSX:typeof import("xlsx")){if(v instanceof Date&&Number.isFinite(v.getTime()))return iso(v.getUTCFullYear(),v.getUTCMonth()+1,v.getUTCDate());if(typeof v==="number"&&Number.isFinite(v)){const x=XLSX.SSF.parse_date_code(v);if(x)return iso(x.y,x.m,x.d)}const raw=text(v);let m=raw.match(/^(\d{4})-(\d{2})-(\d{2})/);if(m)return iso(+m[1],+m[2],+m[3]);m=raw.match(/^(\d{2})\/(\d{2})\/(\d{4})$/);return m?iso(+m[3],+m[2],+m[1]):null}
function cleanName(v:unknown){return text(v).replace(/^\d{2}\/\d{2}\/\d{4}\s+/,"").replace(/\s*-\s*PROTESTAD[OA]\b/gi,"").replace(/\s*\(\s*\d+\s*\)\s*$/,"").trim()}
function cpf(v:unknown){const x=String(v??"").replace(/\D/g,"");return x.length===11?x:null}
function findIndex(header:unknown[],...parts:string[]){for(let i=0;i<header.length;i++){const k=normalize(header[i]);if(parts.every(p=>k.includes(p)))return i}return -1}
function monthlyHeader(rows:unknown[][]){for(let i=0;i<Math.min(rows.length,12);i++){const keys=(rows[i]??[]).map(normalize);if(keys.includes("vencimento")&&keys.includes("paciente"))return i}return -1}
function negotiationHeader(rows:unknown[][]){for(let i=0;i<rows.length;i++){const keys=(rows[i]??[]).map(normalize);if(keys.some(k=>k.includes("datadanegociacao"))&&keys.includes("paciente"))return i}return -1}
export async function parseCollectionsWorkbook(file:File):Promise<CollectionsWorkbookParseResult>{const XLSX=await import("xlsx");const wb=XLSX.read(await file.arrayBuffer(),{type:"array",cellDates:true});const parsed:ParsedCollectionRow[]=[];const negotiations:ParsedNegotiation[]=[];const sheets:string[]=[];for(const sheetName of wb.SheetNames){const rows=XLSX.utils.sheet_to_json<unknown[]>(wb.Sheets[sheetName],{header:1,defval:"",raw:true});const h=monthlyHeader(rows);if(h>=0){const header=rows[h]??[];const di=findIndex(header,"vencimento"),pi=findIndex(header,"paciente"),ci=findIndex(header,"cpf","paciente"),ri=findIndex(header,"responsavel"),fi=findIndex(header,"formadepagamento"),oi=findIndex(header,"valoremaberto"),vi=findIndex(header,"valorrecebido"),si=findIndex(header,"status"),ni=findIndex(header,"observacoes");for(let r=h+1;r<rows.length;r++){const row=rows[r]??[];const raw=text(row[pi]),due=parseDate(row[di],XLSX);if(!raw||!due)continue;const patientName=cleanName(raw);if(patientName.length<2)continue;const open=Math.round(moneyNumber(row[oi])*100),received=vi>=0?Math.round(moneyNumber(row[vi])*100):0,status=si>=0?text(row[si]):"",notes=ni>=0?text(row[ni]):"";parsed.push({dueDate:due,patientName,cpf:ci>=0?cpf(row[ci]):null,responsible:ri>=0?text(row[ri])||null:null,paymentMethod:fi>=0?text(row[fi])||null:null,openAmountCents:open,receivedAmountCents:received,notes:notes||null,protested:/protestad[oa]/i.test(raw)||/protest/i.test(`${status} ${notes}`),settled:/quitad[oa]|\bpago\b|\bpaga\b/i.test(status)||(open>0&&received>=open),sourceSheet:sheetName,sourceRow:r+1,unit:"Sorocaba"})}sheets.push(sheetName);continue}if(normalize(sheetName).includes("controledenegociacoes")){const nh=negotiationHeader(rows);if(nh<0)continue;const header=rows[nh]??[];const di=findIndex(header,"datadanegociacao"),pi=findIndex(header,"paciente"),mi=findIndex(header,"mesdaregua"),ni=findIndex(header,"valornegociado"),ri=findIndex(header,"valorrecebido"),fi=findIndex(header,"formaderecebimento"),oi=findIndex(header,"observacoes");for(let r=nh+1;r<rows.length;r++){const row=rows[r]??[],date=parseDate(row[di],XLSX),raw=text(row[pi]);if(!date||!raw)continue;negotiations.push({date,patientName:cleanName(raw),monthLabel:mi>=0?text(row[mi])||null:null,negotiatedAmountCents:ni>=0?Math.round(moneyNumber(row[ni])*100):0,receivedAmountCents:ri>=0?Math.round(moneyNumber(row[ri])*100):0,paymentMethod:fi>=0?text(row[fi])||null:null,notes:oi>=0?text(row[oi])||null:null,sourceRow:r+1})}sheets.push(sheetName)}}if(!parsed.length)throw new Error("Não encontrei abas mensais da Régua de Cobrança com Vencimento e Paciente.");return{rows:parsed,negotiations,sheets}}
